version: '3'

volumes:
  node_modules_volume:

services:
  app:
    container_name: nextjs-myblog
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3030:3000
    volumes:
      - .:/workspace:cached
      - node_modules_volume:/workspace/node_modules
    working_dir: /workspace
    tty: true
